import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/header";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" id="mathProject">
      <body className={inter.className}>
        <Toaster />
        <Header />
        {children}
      </body>
      <Script src="//unpkg.com/mathlive" />
    </html>
  );
}
