import LeftSideBar from "@/blocks/LeftSideBar";
import RightMainBar from "@/blocks/RightMainBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <main className="flex h-screen pl-[250px]">
      <LeftSideBar />
      <RightMainBar>{children}</RightMainBar>
    </main>
  );
}
